CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TYPE public.booking_status AS ENUM ('PENDING', 'CONFIRMED', 'CANCELLED');
CREATE TYPE public.tour_difficulty AS ENUM ('Easy', 'Moderate', 'Challenging', 'Expert');
CREATE TYPE public.user_role AS ENUM ('USER', 'ADMIN');

CREATE OR REPLACE FUNCTION public.set_bookings_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_updated_at_custom_packages() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.update_updated_at_column() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

CREATE TABLE public.users (
  user_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username     VARCHAR(255) NOT NULL UNIQUE,
  email        VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255),
  role         public.user_role NOT NULL DEFAULT 'USER',
  created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  google_id    VARCHAR(255) UNIQUE,
  avatar       VARCHAR(500),
  email_verified BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX idx_users_email_lower ON public.users (LOWER(email));

CREATE TABLE public.password_reset_tokens (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER REFERENCES public.users(user_id) ON DELETE CASCADE,
  email      VARCHAR(255) NOT NULL,
  code       VARCHAR(10) NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX idx_password_reset_tokens_email ON public.password_reset_tokens (LOWER(email));
CREATE INDEX idx_password_reset_tokens_expires_at ON public.password_reset_tokens (expires_at);

CREATE TABLE public."Category" (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(255) NOT NULL,
  image       VARCHAR(255) NOT NULL,
  color       VARCHAR(255) NOT NULL,
  "bgColor"   VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  animation   VARCHAR(255) NOT NULL
);

CREATE TABLE public."Place" (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(255) NOT NULL,
  description  TEXT NOT NULL,
  image        VARCHAR(255) NOT NULL,
  "categoryId" INTEGER NOT NULL REFERENCES public."Category"(id) ON DELETE CASCADE
);

CREATE INDEX idx_place_category ON public."Place"("categoryId");

CREATE TABLE public.tour_packages (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  price       NUMERIC(10,2) NOT NULL CHECK (price >= 0),
  duration    INTEGER NOT NULL CHECK (duration > 0),
  image_path  VARCHAR(255),
  category    VARCHAR(100) NOT NULL,
  highlights  JSONB NOT NULL DEFAULT '[]'::jsonb,
  includes    JSONB NOT NULL DEFAULT '[]'::jsonb,
  difficulty  public.tour_difficulty NOT NULL,
  rating      NUMERIC(3,2) NOT NULL DEFAULT 0.00 CHECK (rating >= 0 AND rating <= 5),
  reviews     INTEGER NOT NULL DEFAULT 0 CHECK (reviews >= 0),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.tour_package_images (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id INTEGER NOT NULL REFERENCES public.tour_packages(id) ON DELETE CASCADE,
  image_path VARCHAR(255) NOT NULL,
  alt_text   VARCHAR(255),
  sort_order INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_tour_package_images_package ON public.tour_package_images (package_id, sort_order);

CREATE TABLE public.places (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR(255) NOT NULL,
  description    TEXT,
  image_path     VARCHAR(255),
  category       VARCHAR(100),
  duration       VARCHAR(50),
  location       VARCHAR(255),
  highlights     JSONB NOT NULL DEFAULT '[]'::jsonb,
  price          NUMERIC(10,2) NOT NULL DEFAULT 0.00 CHECK (price >= 0),
  gallery_images JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_places_category ON public.places (category);
CREATE INDEX idx_places_price ON public.places (price);

CREATE TABLE public.custom_places (
  id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                     VARCHAR(150) NOT NULL,
  description              TEXT,
  image_path               VARCHAR(255),
  category                 VARCHAR(40) NOT NULL,
  default_duration_minutes INTEGER CHECK (default_duration_minutes IS NULL OR default_duration_minutes >= 0),
  base_price               NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (base_price >= 0),
  location                 VARCHAR(255),
  highlights               TEXT[] NOT NULL DEFAULT '{}',
  created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.gallery_items (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category    VARCHAR(255) NOT NULL,
  image_path  VARCHAR(255) NOT NULL,
  title       VARCHAR(255) NOT NULL,
  description TEXT
);

CREATE INDEX idx_gallery_items_category ON public.gallery_items (category);

CREATE TABLE public.reviews (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name     VARCHAR(255) NOT NULL,
  "position" VARCHAR(255),
  avatar   VARCHAR(255),
  rating   NUMERIC(2,1) CHECK (rating >= 0 AND rating <= 5),
  text     TEXT NOT NULL
);

CREATE TABLE public.bookings (
  id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id             INTEGER REFERENCES public.tour_packages(id) ON DELETE SET NULL,
  user_id                INTEGER REFERENCES public.users(user_id) ON DELETE SET NULL,
  customer_name          VARCHAR(255) NOT NULL,
  customer_email         VARCHAR(255) NOT NULL,
  customer_phone         VARCHAR(50),
  preferred_date         DATE NOT NULL,
  preferred_end_date     DATE,
  number_of_guests       INTEGER NOT NULL CHECK (number_of_guests > 0),
  special_requests       TEXT,
  status                 public.booking_status NOT NULL DEFAULT 'PENDING',
  payment_status         TEXT NOT NULL DEFAULT 'PENDING',
  booking_reference      VARCHAR(64),
  created_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  receipt_url            TEXT,
  receipt_uploaded_at    TIMESTAMPTZ,
  dietary_preferences    TEXT,
  food_allergies         TEXT,
  food_and_special_requests TEXT,
  CONSTRAINT bookings_payment_status_check
    CHECK (payment_status IN ('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED')),
  CONSTRAINT bookings_preferred_dates_check
    CHECK (preferred_end_date IS NULL OR preferred_end_date >= preferred_date)
);

CREATE UNIQUE INDEX bookings_booking_reference_uq ON public.bookings (booking_reference);
CREATE INDEX idx_bookings_package_id ON public.bookings (package_id);
CREATE INDEX idx_bookings_user_id ON public.bookings (user_id);
CREATE INDEX idx_bookings_status ON public.bookings (status);
CREATE INDEX idx_bookings_payment_status ON public.bookings (payment_status);

CREATE TABLE public.booking_receipts (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id  INTEGER NOT NULL REFERENCES public.bookings(id) ON DELETE CASCADE,
  file_url    TEXT NOT NULL,
  mime_type   TEXT,
  uploaded_by TEXT,
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX booking_receipts_booking_id_idx ON public.booking_receipts (booking_id);

CREATE TABLE public.custom_packages (
  id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name                     VARCHAR(255) NOT NULL,
  description              TEXT,
  total_duration_minutes   INTEGER CHECK (total_duration_minutes IS NULL OR total_duration_minutes >= 0),
  total_duration_label     VARCHAR(50),
  guests                   INTEGER NOT NULL DEFAULT 1 CHECK (guests >= 1),
  contact_email            VARCHAR(255) NOT NULL,
  user_id                  INTEGER REFERENCES public.users(user_id) ON DELETE SET NULL,
  contact_phone            VARCHAR(50),
  start_date               DATE,
  end_date                 DATE,
  food_and_special_requests TEXT,
  additional_info          TEXT,
  status                   TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  quotation_pdf_path       VARCHAR(500),
  created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_custom_packages_user_id ON public.custom_packages (user_id);
CREATE INDEX idx_custom_packages_status ON public.custom_packages (status);

CREATE TABLE public.custom_package_places (
  custom_package_id UUID NOT NULL REFERENCES public.custom_packages(id) ON DELETE CASCADE,
  place_id          INTEGER NOT NULL REFERENCES public.places(id) ON DELETE RESTRICT,
  display_order     INTEGER NOT NULL CHECK (display_order >= 1),
  PRIMARY KEY (custom_package_id, place_id)
);

CREATE INDEX custom_package_places_custom_package_id_idx ON public.custom_package_places (custom_package_id);
CREATE INDEX custom_package_places_place_id_idx ON public.custom_package_places (place_id);

CREATE TRIGGER trg_bookings_set_updated_at
  BEFORE UPDATE ON public.bookings
  FOR EACH ROW EXECUTE FUNCTION public.set_bookings_updated_at();

CREATE TRIGGER trg_tour_packages_set_updated_at
  BEFORE UPDATE ON public.tour_packages
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER trg_custom_packages_set_updated_at
  BEFORE UPDATE ON public.custom_packages
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_custom_packages();

CREATE TRIGGER trg_password_reset_tokens_set_updated_at
  BEFORE UPDATE ON public.password_reset_tokens
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();